// Shared product catalog for index.html and play.html
const STORE = "https://www.teacherspayteachers.com/store/micahs-learning-resources";

// Sorted best-first.
const CATALOG = [
  {slug:"surviving-the-dust-bowl-simulation", img:"surviving-the-dust-bowl-simulation.jpg",
   tag:"Simulation Game", title:"Surviving the Dust Bowl",
   blurb:"Manage a family farm through the Dirty Thirties. Every season brings choices - plant, conserve, borrow, or leave - and the land remembers all of them.",
   tpt:"https://www.teacherspayteachers.com/Product/Dust-Bowl-Interactive-Simulation-Game-Surviving-the-Dirty-Thirties-15161229"},
  {slug:"real-estate-portfolio-manager", img:"real-estate-portfolio-manager.png",
   tag:"Financial Literacy Sim", title:"Real Estate Portfolio Manager",
   blurb:"Build a property portfolio: analyze deals, manage cash flow and debt, and grow equity in a market that moves whether you're ready or not.",
   tpt:"https://www.teacherspayteachers.com/Product/Real-Estate-Portfolio-Manager-Financial-Literacy-Simulation-Game-Grades-9-12-15688300"},
  {slug:"viking-camp-3d-the-voyage-west", img:"viking-camp-3d-the-voyage-west.png",
   tag:"3D Exploration Game", title:"Viking Camp 3D: The Voyage West",
   blurb:"Explore a Viking camp in full 3D, earn wisdom at fact stations, then command a longship voyage west.",
   tpt:"https://www.teacherspayteachers.com/Product/Vikings-3D-Exploration-Game-Viking-Camp-and-Longship-Voyage-Simulation-16914166"},
  {slug:"dust-bowl-digital-dbq", img:"dust-bowl-digital-dbq.png",
   tag:"Digital DBQ", title:"Dust Bowl Digital DBQ",
   blurb:"Analyze photographs, letters, and data, then build an evidence-based essay in this interactive Document-Based Question.",
   tpt:"https://www.teacherspayteachers.com/Product/Dust-Bowl-Digital-DBQ-Primary-Sources-Document-Analysis-Essay-16226529"},
  {slug:"julius-caesar-space-time-investigation", img:"julius-caesar-space-time-investigation.png",
   tag:"Map + Timeline Investigation", title:"Julius Caesar: Power Across Space & Time",
   blurb:"Scrub a timeline and watch Caesar's world move: a living map, a web of allies and rivals, and era case files ending in a historian's verdict.",
   tpt:STORE},
  {slug:"george-washington-space-time-investigation", img:"george-washington-space-time-investigation.png",
   tag:"Map + Timeline Investigation", title:"George Washington: Power Across Space & Time",
   blurb:"Follow Washington from surveyor to president on a synchronized map, timeline, and relationship web - then weigh the evidence yourself.",
   tpt:STORE},
  {slug:"credit-debt-mastery-simulator", img:"credit-debt-mastery-simulator.png",
   tag:"Financial Literacy Sim", title:"Credit & Debt Simulator",
   blurb:"Take out loans, watch a credit score move in real time, and race to pay off debt in this hands-on money simulator.",
   tpt:"https://www.teacherspayteachers.com/Product/Credit-and-Debt-Simulator-Credit-Score-Loans-and-Payoff-Game-16638167"},
  {slug:"1929-crash-investigation-lab", img:"1929-crash-investigation-lab.png",
   tag:"Investigation Lab", title:"1929 Crash Investigation Lab",
   blurb:"Students work as investigators: sift the evidence and primary sources to explain what really triggered the Great Crash.",
   tpt:"https://www.teacherspayteachers.com/Product/1929-Crash-Investigation-Lab-16151751"},
  {slug:"riverside-coffee-cart-economics-simulation", img:"riverside-coffee-cart-economics-simulation.png",
   tag:"Economics Simulation", title:"Riverside Coffee Cart Economics Sim",
   blurb:"Set prices, juggle supply and demand, and feel opportunity cost by running a small business day by day.",
   tpt:"https://www.teacherspayteachers.com/Product/Economics-Simulation-Game-Supply-Demand-Opportunity-Cost-Business-Sim-16569358"},
  {slug:"california-state-history", img:"california-state-history.jpg",
   tag:"State History", title:"California State History",
   blurb:"Interactive maps, a timeline, a quiz, and a primary-source document decoder - a complete state history unit in one page.",
   tpt:"https://www.teacherspayteachers.com/Product/California-State-History-Interactive-Maps-Timeline-Quiz-Document-Decoder-15201318"},
  {slug:"world-war-ii-animated-history-timeline", img:"world-war-ii-animated-history-timeline.png",
   tag:"Animated Timeline", title:"World War II Animated Timeline",
   blurb:"Scroll through 11 major events of World War II in an animated, illustrated timeline experience.",
   tpt:"https://www.teacherspayteachers.com/Product/World-War-II-Animated-History-Timeline-11-Major-Events-Interactive-Scroll-Expe-15665925"}
];

const FREEMAPS = [
  {slug:"california-gold-rush-free-map", title:"California Gold Rush Map",
   blurb:"Map the key sites of the 1849 Gold Rush.", tpt:STORE},
  {slug:"ancient-greece-city-states-free-map", title:"Ancient Greece City-States Map",
   blurb:"Locate Athens, Sparta, and the major city-states.", tpt:STORE},
  {slug:"albert-einstein-life-locations-free-map", title:"Einstein Life Locations Map",
   blurb:"Trace the cities that shaped Einstein's life.", tpt:STORE},
  {slug:"beethoven-vienna-residences-free-map", title:"Beethoven's Vienna Map",
   blurb:"Walk through the Vienna homes where Beethoven composed.", tpt:STORE}
];

const BUNDLES = [
  {title:"Economics & Personal Finance Bundle", emoji:"💰",
   blurb:"Supply & demand game, budgeting activities, and more - the full economics toolkit.",
   tpt:"https://www.teacherspayteachers.com/Product/Economics-Personal-Finance-Bundle-Supply-Demand-Game-Budgeting-Activities-16483375"},
  {title:"Interactive Biography Bundle", emoji:"📚",
   blurb:"Timelines, maps, and quizzes for history's greatest lives. Grades 4-7.",
   tpt:"https://www.teacherspayteachers.com/Product/Biography-Bundle-Interactive-Reading-Timelines-Maps-Quizzes-Grades-4-7-16799631"},
  {title:"Cold War Activities Bundle", emoji:"🌍",
   blurb:"Interactive digital activities, study guides, and maps for the whole Cold War unit.",
   tpt:"https://www.teacherspayteachers.com/Product/Cold-War-Interactive-Digital-Activities-Study-Guides-Maps-Bundle-15581869"},
  {title:"Ancient Greece & Mythology Bundle", emoji:"🏛️",
   blurb:"Gods, city-states, and myths - a complete Ancient Greece companion set.",
   tpt:"https://www.teacherspayteachers.com/Product/Ancient-Greece-Greek-Mythology-Bundle-16298679"},
  {title:"Europe Geography Map Games Bundle", emoji:"🗺️",
   blurb:"France, Germany, Italy, Spain and more - interactive map games for all of Europe.",
   tpt:"https://www.teacherspayteachers.com/Product/Europe-Geography-Map-Games-Bundle-France-Germany-Italy-Spain-and-More-17094287"},
  {title:"ELA Mega Bundle", emoji:"✏️",
   blurb:"Grammar, vocabulary, and reading - interactive ELA activities in one mega pack.",
   tpt:"https://www.teacherspayteachers.com/Product/ELA-Mega-Bundle-Grammar-Vocabulary-Reading-Interactive-Activities-16798523"}
];
